/*
Populates a local JSON array with every food's name.
*/

import React from 'react';
import { Platform} from 'react-native';

export default class PopulateDatabase extends React.Component {
	constructor(){
		super();

global.nameList = [

  "almonds, flaked and ground",
  "asparagus, raw",
  "bacon rashers, back, grilled crispy",
  "bacon rashers, streaky, raw",
  "baked beans, canned in tomato sauce, reduced sugar, reduced salt",
  "baked beans, canned in tomato sauce, with pork sausages",
  "baking fat and margarine (75-90% fat), hard block",
  "basil, fresh",
  "bass, sea, flesh only, baked",
  "bean loaf, mixed beans, homemade",
  "beans, butter, dried, boiled in unsalted water",
  "beans, green, raw",
  "beef, fillet steak, raw, lean",
  "beef, mince, microwaved",
  "beef, rump steak, barbecued, lean",
  "beef, silverside, raw, lean",
  "beef, sirloin joint, roasted, lean and fat",
  "bolognese sauce (with meat), made with extra lean minced beef, homemade",
  "broccoli, green, boiled in unsalted water",
  "broccoli, purple sprouting, raw",
  "brownies, chocolate, homemade",
  "brussels sprouts, raw",
  "butter, spreadable (75-80% fat)",
  "butter, unsalted",
  "butteroil, unsalted",
  "cabbage, average, raw",
  "cabbage, green, raw",
  "cabbage, red, cooked with apple",
  "cabbage, white, boiled in unsalted water",
  "cabbage, white, raw",
  "carrots, old, microwaved",
  "carrots, young, boiled in unsalted water",
  "carrots, young, canned in water, re-heated, drained",
  "carrots, young, raw",
  "cashew fruit, flesh only",
  "casserole, pork and apple, homemade",
  "casserole, rabbit, homemade",
  "casserole, sweet potato and green banana, homemade",
  "cauliflower, raw",
  "cereal bars, with fruit and/or nuts, no chocolate, unfortified",
  "cheese sauce, packet mix, made up with semi-skimmed milk, homemade",
  "cheese, cheddar type, half fat",
  "cheese, cheddar, english",
  "cheese, cottage, plain",
  "chicken, breast, casseroled, meat only",
  "chicken, breast, grilled, meat and skin",
  "chicken, breast, strips, stir-fried in corn oil",
  "chicken, leg quarter, casseroled, meat only",
  "chicken, wing quarter, casseroled, meat and skin",
  "chilli sauce",
  "chital, raw",
  "cho cho fritters, fried in rapeseed oil, homemade",
  "cod, flesh only, baked, weighed with bones and skin",
  "cod, in batter, fried in dripping, takeaway",
  "cod, in batter, fried in sunflower oil, takeaway",
  "coriander leaves, fresh",
  "coriander seeds",
  "corn fritters, fried in rapeseed oil, homemade",
  "courgette, fried in corn oil",
  "courgettes with eggs, homemade",
  "cream substitute, single",
  "cream, dairy, extra thick (24% fat)",
  "cream, fresh, whipping",
  "creme fraiche, half fat",
  "cumin seeds",
  "curly kale, boiled in unsalted water",
  "curry paste",
  "curry powder, mixed flavours",
  "curry, almond, homemade",
  "curry, beef, retail, reheated, with rice",
  "curry, bhindi subji, homemade",
  "curry, chicken tandoori, retail, reheated",
  "curry, chicken, average, takeaway",
  "dill, dried",
  "dips, sour-cream based, assorted flavours",
  "dressing, french, fat free",
  "dressing, yogurt, homemade",
  "eggs, chicken, white, boiled",
  "eggs, chicken, whole, fried, without fat",
  "eggs, chicken, whole, poached",
  "eggs, chicken, whole, raw",
  "fat spread, low fat (26-39%), not polyunsaturated, with olive oil",
  "fennel, florence, boiled in unsalted water",
  "fig rolls",
  "fish fingers, cod, grilled/baked",
  "fish fingers, pollock, grilled",
  "flour, wheat, white, self raising",
  "flour, wheat, wholemeal",
  "flour, wheat, wholemeal, bread/strong",
  "flying fish, raw",
  "garlic mushrooms, not coated, homemade",
  "garlic, raw",
  "gateau, chocolate based, frozen",
  "ginger, ground",
  "gingerbread, homemade",
  "green beans, dried",
  "haggis, boiled",
  "hake, flesh only, grilled",
  "ham, gammon joint, raw",
  "houmous",
  "lamb, leg, whole, roasted, lean and fat",
  "lamb, mince, stewed with onions",
  "lamb, neck fillet, raw, lean",
  "lasagne, homemade, with extra lean minced beef",
  "lasagne, spinach, wholemeal, homemade",
  "lemon chicken, homemade",
  "lime juice cordial, diluted",
  "marmalade",
  "mchicha, homemade",
  "milk, sheeps, raw",
  "milk, soya, non-dairy alternative to milk, sweetened, fortified",
  "milk, whole, pasteurised, average",
  "milkshake, thick, takeaway",
  "mint, fresh",
  "mixed curry spices",
  "mixed herbs, dried",
  "molasses",
  "mushrooms, chinese, dried, raw",
  "mushrooms, white, raw",
  "mustard leaves, raw",
  "mustard, powder, made up",
  "mustard, wholegrain",
  "nectarines, flesh and skin, raw",
  "nuts, mixed",
  "oil, vegetable, average",
  "oil, walnut",
  "omelette, spanish, homemade",
  "onions, boiled in unsalted water",
  "onions, fried in corn oil",
  "onions, pickled, drained",
  "orange juice, ambient, uht",
  "oregano, fresh",
  "ortaniques, flesh only",
  "pakora, vegetable, takeaway and restaurant",
  "paratha, homemade",
  "parsley, fresh",
  "parsnip, boiled in unsalted water",
  "partridge, meat only, roasted",
  "pasta with meat and tomato sauce, homemade",
  "pasta, egg, fresh, filled with cheese and tomato, boiled in unsalted water",
  "pasta, egg, white, dried, raw",
  "pasta, white,  twists, fusilli, dried, boiled in unsalted water",
  "pasta, white, dried, raw",
  "pasta, wholewheat, spaghetti, dried, raw",
  "pastry, filo, retail, uncooked",
  "pastry, flaky/puff, retail, uncooked",
  "pastry, shortcrust, retail, uncooked",
  "peanuts, kernel only, plain, weighed with shells",
  "peas, canned in water, re-heated, drained",
  "peas, dried, boiled in unsalted water",
  "peas, frozen, microwaved",
  "peas, mange-tout, raw",
  "peas, mange-tout, stir-fried in rapeseed oil",
  "peas, marrowfat, canned, re-heated, drained",
  "peas, mushy, canned, re-heated",
  "peas, sugar-snap, raw",
  "pecan nuts, kernel only",
  "pepper, capsicum, red, boiled in unsalted water",
  "pepper, capsicum, yellow, boiled in unsalted water",
  "pepper, cayenne, ground",
  "pepper, white",
  "peppermint creams, homemade",
  "peppers, capsicum, chilli, red, raw",
  "peppers, capsicum, green, boiled in unsalted water",
  "peppers, green, stuffed with rice, homemade",
  "pickle, sweet",
  "pie, chicken, individual, baked",
  "pie, cottage/shepherds, reheated",
  "pie, fish, white fish, homemade",
  "pie, fish, white fish, retail, baked",
  "pie, fruit, individual, retail",
  "pie, spinach, homemade",
  "pie, steak and kidney, single crust, homemade",
  "pie, turkey, single crust, homemade",
  "pizza, cheese and tomato, retail",
  "pizza, chicken topped, retail",
  "pizza, fish topped, takeaway",
  "pizza, meat topped, retail and takeaway",
  "pizza, tomato, homemade",
  "pizza, vegetarian, retail and takeaway",
  "plaice, flesh only, baked",
  "pork, leg joint, roast, lean and fat",
  "pork, loin joint, raw, lean and fat",
  "pork, spare rib chops, braised, lean",
  "potato cakes, fried in rapeseed oil",
  "potato chips, fine cut, from fast food outlets",
  "potato chips, fine cut, frozen, fried in corn oil",
  "potato chips, oven ready, no batter, baked",
  "potato chips, oven ready, with batter, baked",
  "potato chips, straight cut, frozen, fried in corn oil",
  "potato crisps, low fat",
  "potato croquettes, fried in blended oil",
  "potato powder, instant, raw",
  "potatoes, old, baked, flesh and skin",
  "potatoes, old, boiled in salted water, flesh only",
  "potatoes, old, boiled in unsalted water, flesh only",
  "potatoes, old, mashed with reduced fat spread",
  "potatoes, old, potato wedges, with skin, cooked in sunflower oil, homemade",
  "potatoes, old, wedges, with skin, homemade, cooked in rapeseed oil",
  "rice, brown, easy cook, raw",
  "rice, brown, wholegrain, raw",
  "rice, red, raw",
  "rice, white, basmati, easy cook, boiled in unsalted water",
  "rice, white, basmati, easy cook, raw",
  "rice, white, long grain, easy cook, boiled in unsalted water",
  "rice, white, long grain, easy cook, raw",
  "roe, cod, hard, coated in batter, fried",
  "rosemary, fresh",
  "roulade, spinach",
  "sage, dried, ground",
  "sage, fresh",
  "sago, raw",
  "salad cream, reduced fat",
  "salted fish, chinese, bones removed, steamed",
  "sauce, chinese cook in, sweet & sour",
  "sauce, pasta, tomato based, napoletana",
  "sausages, beef, grilled",
  "sausages, beef, raw",
  "sausages, pork, chilled, grilled",
  "sausages, pork, frozen, fried in vegetable oil",
  "sausages, premium, grilled",
  "sausages, premium, raw",
  "shandy, 50% lager, homemade",
  "shepherds pie, vegetable",
  "shepherds pie, vegetable, retail",
  "sherry, medium",
  "spaghetti bolognese, retail, meat and sauce only, reheated",
  "spinach, baby, boiled in unsalted water",
  "spinach, baby, raw",
  "spinach, dried",
  "spinach, mature, boiled in unsalted water",
  "spinach, mature, raw",
  "spirits, 40% volume",
  "spring onions, bulbs and tops, raw",
  "squash, butternut, boiled in unsalted water",
  "stew, beef, made with lean beef, homemade",
  "stew, irish, homemade",
  "stock cubes, chicken",
  "stock cubes, chicken, made up with water",
  "stock gel",
  "suet, vegetable, reduced fat",
  "sultanas",
  "sunflower seeds, toasted",
  "sweet potato, flesh only, boiled in unsalted water",
  "sweetbread, lamb, fried in corn oil",
  "sweetcorn, baby, stir-fried in rapeseed oil",
  "sweetcorn, dried",
  "tannia, raw",
  "tarragon, fresh",
  "tart, bakewell, homemade",
  "thyme, fresh",
  "tigernuts",
  "toad in the hole, made with skimmed milk and reduced fat sausages, homemade",
  "tomato puree",
  "tomato sauce, homemade",
  "tomatoes, cherry, raw",
  "tomatoes, standard, fried in corn oil",
  "tomatoes, stuffed with rice",
  "turkey, self-basting, light meat, roasted",
  "turkish delight, with nuts, homemade",
  "turnip tops, boiled in unsalted water",
  "turnip, flesh only, raw",
  "vegetables, mixed, stir-fry type, frozen, fried in rapeseed oil",
  "vegetables, stir-fried, takeaway",
  "wafers, plain ice cream wafers, not filled",
  "walnuts, kernel only, weighed with shells",
  "yam, flesh only, boiled in unsalted water",
  "yogurt, low fat, fruit",
  "yogurt, low fat, toffee",
  "yogurt, whole milk, fruit",
  "yogurt, whole milk, twin pot, not fruit"
]}}
