/*
Populates a local JSON array with every food's name.
*/

import React from 'react';
import { Platform} from 'react-native';

export default class PopulateDatabase extends React.Component {
	constructor(){
		super();

global.nameList = [

  "allspice, ground",
  "asparagus, grilled",
  "bacon rashers, back, grilled",
  "bacon rashers, streaky, grilled",
  "baked beans, canned in tomato sauce",
  "baked beans, canned in tomato sauce, reduced sugar, reduced salt",
  "baked beans, canned in tomato sauce, with pork sausages",
  "basil, dried, ground",
  "basil, fresh",
  "bay leaf, dried",
  "beans, butter, canned, re-heated, drained",
  "beans, green, boiled in unsalted water",
  "beef, fillet steak, grilled, lean and fat",
  "beef, mince, frozen, stewed",
  "beef, minced, stewed with onions, extra lean",
  "beef, silverside, pot-roasted, lean and fat",
  "beef, sirloin joint, roasted, lean",
  "bolognese sauce (with meat), homemade",
  "broccoli, green, boiled in salted water",
  "broccoli, purple sprouting, boiled in unsalted water",
  "brown sauce, reduced salt/sugar",
  "brussels sprouts, boiled in unsalted water",
  "butter, salted",
  "butter, spreadable, light (60% fat)",
  "butter, unsalted",
  "cabbage, average, boiled in unsalted water",
  "cabbage, green, boiled in unsalted water",
  "cabbage, red, boiled in unsalted water",
  "cabbage, red, raw",
  "cabbage, white, boiled in unsalted water",
  "carrots, old, boiled in unsalted water",
  "carrots, old, raw",
  "carrots, young, boiled in unsalted water",
  "carrots, young, canned in water, re-heated, drained",
  "carrots, young, raw",
  "casserole, beef, made with cook-in sauce",
  "casserole, pork, made with cook-in sauce",
  "casserole, sausage, homemade",
  "cauliflower, boiled in unsalted water",
  "celery, raw",
  "cheese sauce, made with whole milk, homemade",
  "cheese, cheddar type, 30% less fat",
  "cheese, cheddar type, half fat",
  "cheese, cheddar, english",
  "chicken, breast, casseroled, meat and skin, weighed with bone",
  "chicken, breast, grilled without skin, meat only",
  "chicken, breast, grilled, meat and skin",
  "chicken, leg quarter, casseroled, meat and skin, weighed with bone",
  "chicken, whole, roasted, meat and skin, weighed with bone",
  "chilli powder",
  "chinese 5 spice",
  "chives, fresh",
  "cod, flesh only, baked",
  "cod, in batter, baked",
  "cod, in batter, fried in rapeseed oil",
  "coriander leaves, dried",
  "coriander leaves, fresh",
  "coriander seeds",
  "courgette, fried in butter",
  "courgette, roasted in rapeseed oil",
  "cream substitute, double",
  "cream substitute, single",
  "cream, fresh, single",
  "creme fraiche, full fat",
  "cucumber, raw, flesh and skin",
  "cumin seeds",
  "curry leaves, fresh",
  "curry powder",
  "curry powder, mixed flavours",
  "curry, beef, retail, reheated",
  "curry, beef, retail, reheated, with rice",
  "curry, chicken korma, homemade",
  "curry, chicken, average, retail, reheated with rice",
  "dill seeds",
  "dill, fresh",
  "dressing, french",
  "dressing, thousand island",
  "eggs, chicken, scrambled, with semi-skimmed milk",
  "eggs, chicken, whole, fried in sunflower oil",
  "eggs, chicken, whole, fried, without fat",
  "eggs, chicken, whole, poached",
  "fat spread, low fat (26-39%), not polyunsaturated, including dairy type",
  "fennel seeds",
  "fenugreek seeds",
  "fish fingers, cod, fried in sunflower oil",
  "fish fingers, cod, grilled/baked",
  "flour, wheat, white, plain, soft",
  "flour, wheat, white, self raising",
  "flour, wheat, wholemeal",
  "flour, wheat, wholemeal, self raising",
  "garam masala",
  "garlic powder",
  "garlic, raw",
  "ginger, fresh",
  "ginger, ground",
  "gravy instant granules, made up with water",
  "haddock, in batter, fried in sunflower oil",
  "haggis, boiled",
  "ham, gammon joint, boiled",
  "hot pot, lamb/beef with potatoes, retail, reheated",
  "lamb, leg, whole, roasted well done, lean and fat",
  "lamb, mince, stewed",
  "lamb, mince, stewed with onions",
  "lasagne, homemade",
  "lasagne, retail, reheated",
  "leeks, roasted in rapeseed oil",
  "lettuce, average, raw",
  "marjoram, dried",
  "mayonnaise, standard, retail",
  "milk, semi-skimmed, uht",
  "milk, skimmed, uht",
  "milk, soya, non-dairy alternative to milk, unsweetened, fortified",
  "milk, whole, uht",
  "mint, dried",
  "mint, fresh",
  "mixed curry spices",
  "mixed herbs, dried",
  "mushroom, dried",
  "mushrooms, white, fried in salted butter",
  "mustard leaves, boiled in unsalted water",
  "mustard seeds",
  "mustard, smooth",
  "mustard, wholegrain",
  "nutmeg, ground",
  "oil, sunflower",
  "oil, vegetable, average",
  "omelette, plain, homemade",
  "onions, baked",
  "onions, fried in butter",
  "onions, fried in sunflower oil",
  "onions, raw",
  "oregano, dried, ground",
  "oregano, fresh",
  "pak choi, steamed",
  "paprika",
  "parsley, dried",
  "parsley, fresh",
  "parsnip, roasted in rapeseed oil",
  "pasta with ham and mushroom sauce, homemade",
  "pasta with meat and tomato sauce, homemade",
  "pasta, egg, fresh, raw",
  "pasta, spaghetti, canned, in tomato sauce",
  "pasta, white, dried, boiled in unsalted water",
  "pasta, wholewheat, spaghetti, dried, boiled in unsalted water",
  "pastry, filo, retail, cooked",
  "pastry, flaky/puff, retail, cooked",
  "pastry, shortcrust, retail, cooked",
  "peanuts, kernel only, plain, unsalted",
  "peas, boiled in unsalted water",
  "peas, canned in water, re-heated, drained",
  "peas, frozen, boiled in unsalted water",
  "peas, mange-tout, boiled in unsalted water",
  "peas, mange-tout, raw",
  "peas, mange-tout, stir-fried in rapeseed oil",
  "peas, marrowfat, canned, re-heated, drained",
  "peas, sugar-snap, boiled in unsalted water",
  "peas, sugar-snap, raw",
  "pepper, black",
  "pepper, capsicum, red, raw",
  "pepper, capsicum, yellow, raw",
  "pepper, cayenne, ground",
  "pepper, white",
  "peppers, capsicum, chilli, green, raw",
  "peppers, capsicum, chilli, red, raw",
  "peppers, capsicum, green, raw",
  "piccalilli",
  "pie, chicken and mushroom, single crust, homemade",
  "pie, cottage, homemade",
  "pie, cottage/shepherds, reheated",
  "pie, fish, white fish, homemade",
  "pie, fish, white fish, retail, baked",
  "pie, quorn and vegetable",
  "pie, steak and kidney, double crust, homemade",
  "pie, steak and kidney, single crust, homemade",
  "pizza base, raw",
  "pizza, cheese and tomato, retail",
  "pizza, chicken topped, retail",
  "pizza, ham and pineapple, retail",
  "pizza, meat topped, retail and takeaway",
  "pizza, tomato, homemade",
  "pizza, vegetarian, retail and takeaway",
  "pork, leg joint, raw, lean and fat, weighed with bone",
  "pork, loin joint, pot-roasted, lean and fat",
  "pork, mince, stewed",
  "pot savouries, made up",
  "potato chips, crinkle cut, frozen, fried in corn oil",
  "potato chips, fine cut, frozen, fried in blended vegetable oil",
  "potato chips, microwave, cooked",
  "potato chips, oven ready, no batter, baked",
  "potato chips, straight cut, frozen, fried in blended oil",
  "potato crisps, fried in sunflower oil",
  "potato crisps, low fat",
  "potato powder, instant, made up with whole milk",
  "potatoes, new, frozen, `roast in corn oil",
  "potatoes, old, baked, flesh only, weighed with skin",
  "potatoes, old, boiled in salted water, flesh only",
  "potatoes, old, mashed with butter",
  "potatoes, old, microwaved, flesh and skin",
  "potatoes, old, roasted in sunflower oil, flesh only",
  "rice, brown, easy cook, boiled in unsalted water",
  "rice, brown, wholegrain, boiled in unsalted water",
  "rice, ready-cooked, plain, re-heated",
  "rice, white, basmati, boiled in unsalted water",
  "rice, white, basmati, easy cook, boiled in unsalted water",
  "rice, white, long grain, boiled in unsalted water",
  "rice, white, long grain, easy cook, boiled in unsalted water",
  "rocket, raw",
  "rosemary, dried",
  "rosemary, fresh",
  "saffron",
  "sage, dried, ground",
  "sage, fresh",
  "salad cream",
  "salt",
  "sauce, cheese, packet mix, dry",
  "sauce, pasta, tomato based, for bolognese",
  "sausages, beef, fried in vegetable oil",
  "sausages, beef, grilled",
  "sausages, pork, chilled, fried in vegetable oil",
  "sausages, pork, chilled, grilled",
  "sausages, premium, fried in vegetable oil",
  "sausages, premium, grilled",
  "shallots, raw",
  "shepherds pie, homemade",
  "shepherds pie, vegetable",
  "shepherds pie, vegetable, retail",
  "spaghetti bolognese, homemade",
  "spaghetti bolognese, retail, reheated, with spaghetti",
  "spinach, baby, boiled in unsalted water",
  "spinach, baby, raw",
  "spinach, frozen, boiled in unsalted water",
  "spinach, mature, boiled in unsalted water",
  "spinach, mature, raw",
  "spring greens, raw",
  "squash, butternut, baked",
  "stew, beef, homemade",
  "stew, beef, with dumplings, homemade",
  "stock cubes, beef",
  "stock cubes, chicken",
  "stock cubes, vegetable",
  "suet, shredded",
  "sugar, white",
  "sunflower seeds",
  "sweet potato, baked",
  "sweet potato, wedges, flesh and skin, baked in rapeseed oil",
  "sweetcorn, baby, boiled in unsalted water",
  "sweetcorn kernels, canned in water, drained",
  "tamarind pulp, flesh only",
  "tarragon, dried, ground",
  "tarragon, fresh",
  "thyme, dried, ground",
  "thyme, fresh",
  "toad in the hole, homemade",
  "tomato ketchup",
  "tomato puree",
  "tomatoes, canned, whole contents",
  "tomatoes, cherry, raw",
  "tomatoes, standard, raw",
  "turkey, mince, stewed",
  "turkey, whole, roasted, meat and skin, weighed with bone",
  "turmeric, ground",
  "turnip, boiled in unsalted water",
  "vegetables, mixed, frozen, boiled in unsalted water",
  "vegetables, mixed, stir-fry type, frozen, fried in rapeseed oil",
  "vinegar",
  "walnuts, kernel only",
  "yam, baked",
  "yogurt, greek style, plain",
  "yogurt, low fat, plain",
  "yogurt, virtually fat free/diet, plain",
  "yogurt, whole milk, plain",
  "yorkshire pudding, made with whole milk"
]}}
